// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa-UTHEPdJhkPg80IJVxFvQON0Obrx9qY',
    appId: '1:124582574517:web:e3ade419bb62c1f2bb81fc',
    messagingSenderId: '124582574517',
    projectId: 'fir-p4etps3',
    authDomain: 'fir-p4etps3.firebaseapp.com',
    storageBucket: 'fir-p4etps3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_enObfZmm4KNDkuW5EjoQc4571-QCIIM',
    appId: '1:124582574517:android:0e296f4dca086e80bb81fc',
    messagingSenderId: '124582574517',
    projectId: 'fir-p4etps3',
    storageBucket: 'fir-p4etps3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYFKwG-MYVKRAeu-9Wu0f_GbxtVCMcSkI',
    appId: '1:124582574517:ios:faae50e9359607efbb81fc',
    messagingSenderId: '124582574517',
    projectId: 'fir-p4etps3',
    storageBucket: 'fir-p4etps3.appspot.com',
    iosClientId: '124582574517-fbj4u8hn52p1pjillf3k80d7i9c6bl0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterParcial42526232018',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYFKwG-MYVKRAeu-9Wu0f_GbxtVCMcSkI',
    appId: '1:124582574517:ios:e18518775f649120bb81fc',
    messagingSenderId: '124582574517',
    projectId: 'fir-p4etps3',
    storageBucket: 'fir-p4etps3.appspot.com',
    iosClientId: '124582574517-dv44dlkb6ulj29o6u06jdb89slrllcl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterParcial42526232018.RunnerTests',
  );
}
